---
services:
  io_gateway:
    image: bwdesigngroup/ignition-docker-iiot:8.1.36
    hostname: io_gateway
    volumes:
      - ./ignition-data:/workdir
      - ./backups/io_gateway.gwbk:/restore.gwbk
    environment:
      SYMLINK_GITIGNORE: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: io_gateway
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: io_gateway.localtest.me
      GATEWAY_MODULES_ENABLED: allen-bradley-drivers,bacnet-driver,opc-ua,tag-historian,web-developer
      IIOT_MODULES_ENABLED: mqtt-transmission
    labels:
      traefik.enable: "true"
      traefik.hostname: "io_gateway"
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy

  database:
    image: postgres
    hostname: postgres
    volumes:
      - ./database/init-sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: P@ssword1!
      POSTGRES_USER: postgres
    
  liquibase:
    image: liquibase/liquibase
    depends_on:
      - database
    volumes:
      - ./database:/database
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "liquibase", "--defaultsFile=/database/liquibase/liquibase.docker.properties", "update"]
  
  # Uncomment the following lines to enable pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    labels:
      traefik.enable: "true"
      traefik.hostname: "pgadmin"
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
